import { Inter } from "next/font/google";
import "./globals.css";
import { InterestContextProvider } from "./lib/interestContext";
import {  StateContextProvider } from "./lib/stateContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "G-Sport",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <InterestContextProvider>
        <StateContextProvider>
          <body className={inter.className}>{children}</body>
        </StateContextProvider>
      </InterestContextProvider>
    </html>
  );
}
